
- name: Validate STC_FLAVOR
  assert:
    that: 
      - lookup('env','STC_FLAVOR') == 'mini'
    msg: "STC_FLAVOR should be 'mini'"    

- name: Validate env variables
  assert:
    that: 
      - lookup('env', item ) is defined
    msg: "Env variable {{ item }} is NOT defined!"
  with_items:
    - OS_USERNAME
    - OS_PASSWORD
    - OS_AUTH_URL
    - OS_PROJECT_NAME
    - OS_USER_DOMAIN_NAME
    - OS_PROJECT_DOMAIN_NAME
    - OS_IDENTITY_API_VERSION
    - STC_RHN_PASSWORD
    - STC_RHN_USERNAME
    - STC_SUBSCRIPTION_POOL_ID

- name: Check connection to openstack api 
  command: "curl -s -o /dev/null --connect-timeout 3 {{ lookup('env', 'OS_AUTH_URL' ) }}"
  args:
    warn: false # set warn=false to prevent warning


# - name: Validate masters
#   assert:
#     that:
#       - (master_count == 1) or (master_count == 3)
#     msg: "Master count is currently {{ master_count }} but must be 1 or 3"

# - name: Validate infras
#   assert:
#     that:
#       - (infra_count >= 1 ) 
#       - (infra_count <= 3)
#     msg: "Infra count s currently {{ infra_count }} but must be between 1 and 3"

# - name: Validate nodes
#   assert:
#     that:
#       - (node_count >= 1 ) 
#     msg: "Node count {{ node_count }} must be >= 1"

# - name: Validate OpenShift HA
#   assert:
#     that:
#       - (master_count == 3) and (infra_count > 1)
#     msg: "OpenShift HA requires 3 masters and at least 2 infra nodes"
#   when: openshift_ha

#- name: Validate Registry HA
#  assert:
#    that:
#      - (registry_replicas > 1 )
#    msg: "OpenShift HA requires at least 2 registry replicas"
#  when: openshift_ha
