- name: Ensure nc is installed
  yum:
    name: nc
    state: present
- name: Start nc -l to all valid ports
  shell: "nc -l {{item}} >/dev/null 2>&1 &"
  async: -1
  poll: -1
  with_items:
  - "{{firewall_ports}}"
