- name: Install packages
  yum:
    name: "{{item}}"
    state: latest
  with_items:
  - "{{ packages }}"
  - "{{ packages_jumphost }}"
- name: update bastion packages
  yum:
    name: '*'
    state: latest
